# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BLBMoVMTN8wmM1tYhpRj9Wp8PIQpnz7M
"""

from google.colab import files
uploaded = files.upload()
from google.colab import files
uploaded = files.upload()

# ============================================================
# SCORE AGRO-CLIMATIQUE + JOINTURE SPATIALE AVEC LES UNITES FONCIERES
# ============================================================

!pip -q install geopandas pyogrio fiona shapely mapclassify

import os
import math
import calendar
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import geopandas as gpd

warnings.filterwarnings("ignore")

# -----------------------------
# 1) FICHIERS
# -----------------------------
def find_file(possible_names):
    search_dirs = ["/content", "/mnt/data", "."]
    for d in search_dirs:
        for name in possible_names:
            p = Path(d) / name
            if p.exists():
                return str(p)
    raise FileNotFoundError(f"Fichier introuvable parmi : {possible_names}")

csv_path = find_file([
    "DECADAGRO_26_latest-2025-2026.csv",
    "DECADAGRO_26_latest_2025_2026.csv"
])

gpkg_path = find_file([
    "TUP_SCoT_RPB_CLEAN.gpkg",
    "TUP_SCOT_RPB_CLEAN.gpkg"
])

print("CSV trouvé :", csv_path)
print("GPKG trouvé :", gpkg_path)

# -----------------------------
# 2) LECTURE ET NETTOYAGE DU CSV
# -----------------------------
df = pd.read_csv(csv_path, sep=";", encoding="utf-8", low_memory=False)

df.columns = [c.strip().upper() for c in df.columns]

expected_cols = [
    "NUM_POSTE", "NOM_USUEL", "LAT", "LON", "ALTI", "AAAAMM", "NUM_DECADE",
    "RR", "TN", "TX", "TSVM", "ETP"
]
missing = [c for c in expected_cols if c not in df.columns]
if missing:
    raise ValueError(f"Colonnes manquantes dans le CSV : {missing}")

num_cols = ["NUM_POSTE", "LAT", "LON", "ALTI", "AAAAMM", "NUM_DECADE", "RR", "TN", "TX", "TSVM", "ETP"]
for c in num_cols:
    df[c] = pd.to_numeric(df[c], errors="coerce")

df = df.drop_duplicates()

# Nettoyage géographique et temporel minimal
df = df[
    df["LAT"].between(-90, 90)
    & df["LON"].between(-180, 180)
    & df["NUM_DECADE"].isin([1, 2, 3])
    & df["AAAAMM"].notna()
].copy()

df["YEAR"] = (df["AAAAMM"] // 100).astype(int)
df["MONTH"] = (df["AAAAMM"] % 100).astype(int)
df = df[df["MONTH"].between(1, 12)].copy()

# Nombre de jours de la décade
def days_in_decade(year, month, decade):
    last_day = calendar.monthrange(int(year), int(month))[1]
    if decade == 1:
        return 10
    elif decade == 2:
        return 10
    else:
        return last_day - 20

df["DAYS_DECADE"] = df.apply(lambda r: days_in_decade(r["YEAR"], r["MONTH"], r["NUM_DECADE"]), axis=1)


# priorité à TSVM si présent, sinon moyenne de TN et TX
df["TM_DEC"] = df["TSVM"]
mask_tm_missing = df["TM_DEC"].isna()
df.loc[mask_tm_missing, "TM_DEC"] = (df.loc[mask_tm_missing, "TN"] + df.loc[mask_tm_missing, "TX"]) / 2

# Contrôle de cohérence simple
df.loc[df["RR"] < 0, "RR"] = np.nan
df.loc[(df["TN"] < -40) | (df["TN"] > 50), "TN"] = np.nan
df.loc[(df["TX"] < -40) | (df["TX"] > 60), "TX"] = np.nan
df.loc[(df["TM_DEC"] < -40) | (df["TM_DEC"] > 60), "TM_DEC"] = np.nan
df.loc[df["ETP"] < 0, "ETP"] = np.nan

# Remplissage basique TN / TX / TM par médiane station-mois-décade puis médiane mois-décade
for var in ["TN", "TX", "TM_DEC"]:
    med_station = df.groupby(["NUM_POSTE", "MONTH", "NUM_DECADE"])[var].transform("median")
    med_global = df.groupby(["MONTH", "NUM_DECADE"])[var].transform("median")
    df[var] = df[var].fillna(med_station).fillna(med_global)

# Si TM_DEC manque encore
df["TM_DEC"] = df["TM_DEC"].fillna((df["TN"] + df["TX"]) / 2)

# -----------------------------
# 3) CHOIX DE LA DERNIERE ANNEE COMPLETE
# -----------------------------
# On cherche la dernière année avec les 12 mois présents dans les données
months_per_year = df.groupby("YEAR")["MONTH"].nunique().sort_index()
complete_years = months_per_year[months_per_year == 12].index.tolist()

if not complete_years:
    raise ValueError("Aucune année complète (12 mois) trouvée dans le fichier météo.")

target_year = max(complete_years)
print(f"Année complète retenue pour le scoring : {target_year}")

df = df[df["YEAR"] == target_year].copy()

# -----------------------------
# 4) ESTIMATION DE L'ETP MANQUANTE
# -----------------------------
# Estimation ETP journalière via Hargreaves-Samani, puis conversion en mm par décade
# Utilisée uniquement quand ETP observée est absente.
# C'est une approximation raisonnable pour compléter la base.

def day_of_year_mid_decade(year, month, decade):
    if decade == 1:
        day = 5
    elif decade == 2:
        day = 15
    else:
        last_day = calendar.monthrange(int(year), int(month))[1]
        day = min(25, last_day)
    date = pd.Timestamp(year=int(year), month=int(month), day=int(day))
    return int(date.dayofyear)

def extraterrestrial_radiation_mj(lat_deg, doy):
    # FAO56 - Ra en MJ/m2/jour
    phi = math.radians(lat_deg)
    dr = 1 + 0.033 * math.cos((2 * math.pi / 365) * doy)
    delta = 0.409 * math.sin((2 * math.pi / 365) * doy - 1.39)
    ws = math.acos(max(-1, min(1, -math.tan(phi) * math.tan(delta))))
    gsc = 0.0820  # MJ m-2 min-1
    ra = ((24 * 60) / math.pi) * gsc * dr * (
        ws * math.sin(phi) * math.sin(delta) +
        math.cos(phi) * math.cos(delta) * math.sin(ws)
    )
    return ra

def hargreaves_et0_mm_day(tmin, tmax, tmean, lat_deg, doy):
    # ET0 journalière approximative en mm/jour
    if pd.isna(tmin) or pd.isna(tmax) or pd.isna(tmean) or pd.isna(lat_deg):
        return np.nan
    td = max(tmax - tmin, 0.1)
    ra = extraterrestrial_radiation_mj(lat_deg, doy)
    et0 = 0.0023 * (tmean + 17.8) * math.sqrt(td) * ra
    return max(et0, 0)

df["DOY_MID"] = df.apply(lambda r: day_of_year_mid_decade(r["YEAR"], r["MONTH"], r["NUM_DECADE"]), axis=1)

df["ETP_EST_MM_DAY"] = df.apply(
    lambda r: hargreaves_et0_mm_day(r["TN"], r["TX"], r["TM_DEC"], r["LAT"], r["DOY_MID"]),
    axis=1
)
df["ETP_EST"] = df["ETP_EST_MM_DAY"] * df["DAYS_DECADE"]

# Si ETP observée absente => on prend l'estimation
df["ETP_CLEAN"] = df["ETP"].copy()
df["ETP_SOURCE"] = np.where(df["ETP"].notna(), "observee", "estimee")
df["ETP_CLEAN"] = df["ETP_CLEAN"].fillna(df["ETP_EST"])

# Remplissage final sécurité par médiane station-mois-décade puis globale
med_station_etp = df.groupby(["NUM_POSTE", "MONTH", "NUM_DECADE"])["ETP_CLEAN"].transform("median")
med_global_etp = df.groupby(["MONTH", "NUM_DECADE"])["ETP_CLEAN"].transform("median")
df["ETP_CLEAN"] = df["ETP_CLEAN"].fillna(med_station_etp).fillna(med_global_etp)

# -----------------------------
# 5) AGREGER AU PAS MENSUEL
# -----------------------------
# RR mensuelle = somme des décades
# ETP mensuelle = somme des décades
# TM mensuelle = moyenne pondérée par nb jours
# TN mensuelle = min décadal
# TX mensuelle = max décadal

def weighted_mean(x, w):
    x = np.array(x, dtype=float)
    w = np.array(w, dtype=float)
    mask = np.isfinite(x) & np.isfinite(w)
    if mask.sum() == 0:
        return np.nan
    return np.average(x[mask], weights=w[mask])

monthly = (
    df.groupby(["NUM_POSTE", "NOM_USUEL", "LAT", "LON", "ALTI", "MONTH"], as_index=False)
      .apply(lambda g: pd.Series({
          "RR_MONTH": g["RR"].sum(skipna=True),
          "ETP_MONTH": g["ETP_CLEAN"].sum(skipna=True),
          "TM_MONTH": weighted_mean(g["TM_DEC"], g["DAYS_DECADE"]),
          "TN_MONTH": g["TN"].min(skipna=True),
          "TX_MONTH": g["TX"].max(skipna=True),
          "N_ETP_OBS": int((g["ETP_SOURCE"] == "observee").sum()),
          "N_ETP_EST": int((g["ETP_SOURCE"] == "estimee").sum())
      }))
      .reset_index(drop=True)
)

# -----------------------------
# 6) INDICATEURS ANNUELS PAR STATION
# -----------------------------
station = (
    monthly.groupby(["NUM_POSTE", "NOM_USUEL", "LAT", "LON", "ALTI"], as_index=False)
    .apply(lambda g: pd.Series({
        "RR_ANN_MM": g["RR_MONTH"].sum(skipna=True),
        "ETP_ANN_MM": g["ETP_MONTH"].sum(skipna=True),
        "TM_ANN_C": g["TM_MONTH"].mean(skipna=True),
        "TN_MIN_C": g["TN_MONTH"].min(skipna=True),
        "TX_MAX_C": g["TX_MONTH"].max(skipna=True),
        "ETP_MM_J": g["ETP_MONTH"].sum(skipna=True) / 365.0,
        "NB_MOIS": g["MONTH"].nunique(),
        "ETP_PART_ESTIMEE": g["N_ETP_EST"].sum() / max((g["N_ETP_OBS"].sum() + g["N_ETP_EST"].sum()), 1)
    }))
    .reset_index(drop=True)
)

# Sécurité : on ne garde que les stations avec les 12 mois
station = station[station["NB_MOIS"] == 12].copy()

# -----------------------------
# 7) FONCTIONS DE SCORE
# -----------------------------
# Les scores sont entre 0 et 1.
# Ils traduisent un potentiel agro-climatique général, pas une culture précise.

def trapezoid_score(x, a, b, c, d):
    """
    Score 0..1
    0 avant a
    monte de a à b
    plateau entre b et c
    redescend de c à d
    0 après d
    """
    if pd.isna(x):
        return np.nan
    if x <= a or x >= d:
        return 0.0
    if b <= x <= c:
        return 1.0
    if a < x < b:
        return (x - a) / (b - a)
    if c < x < d:
        return (d - x) / (d - c)
    return 0.0

def descending_penalty(x, good_max, bad_max):
    """
    1 si x <= good_max
    0 si x >= bad_max
    décroissance linéaire entre les deux
    """
    if pd.isna(x):
        return np.nan
    if x <= good_max:
        return 1.0
    if x >= bad_max:
        return 0.0
    return (bad_max - x) / (bad_max - good_max)

def ascending_penalty(x, bad_min, good_min):
    """
    0 si x <= bad_min
    1 si x >= good_min
    croissance linéaire entre les deux
    """
    if pd.isna(x):
        return np.nan
    if x <= bad_min:
        return 0.0
    if x >= good_min:
        return 1.0
    return (x - bad_min) / (good_min - bad_min)

# Sous-scores
# RR favorable 500-800 mm/an
station["S_RR"] = station["RR_ANN_MM"].apply(lambda x: trapezoid_score(x, 300, 500, 800, 1200))

# TM moyenne favorable 15-20°C
station["S_TM"] = station["TM_ANN_C"].apply(lambda x: trapezoid_score(x, 5, 15, 20, 30))

# Tmax favorable <= 30°C, pénalité au-delà, nul vers 38°C
station["S_TX"] = station["TX_MAX_C"].apply(lambda x: descending_penalty(x, 30, 38))

# Tmin favorable >= 0°C, pénalité sous 0, nul vers -5°C
station["S_TN"] = station["TN_MIN_C"].apply(lambda x: ascending_penalty(x, -5, 0))

# ETP moyenne favorable 4-5 mm/jour
station["S_ETP"] = station["ETP_MM_J"].apply(lambda x: trapezoid_score(x, 1.5, 4.0, 5.0, 7.5))

# Score température composite
station["S_TEMP"] = (
    0.60 * station["S_TM"] +
    0.25 * station["S_TX"] +
    0.15 * station["S_TN"]
)

# Score final
station["SCORE_FINAL"] = (
    0.40 * station["S_RR"] +
    0.35 * station["S_TEMP"] +
    0.25 * station["S_ETP"]
) * 100

# Bornage
station["SCORE_FINAL"] = station["SCORE_FINAL"].clip(0, 100).round(1)

# Classes pour QGIS
def score_class(score):
    if pd.isna(score):
        return "NA"
    if score >= 80:
        return "S1 - tres favorable"
    elif score >= 60:
        return "S2 - favorable"
    elif score >= 40:
        return "S3 - moyennement favorable"
    else:
        return "N - peu favorable"

def score_class_num(score):
    if pd.isna(score):
        return 0
    if score >= 80:
        return 4
    elif score >= 60:
        return 3
    elif score >= 40:
        return 2
    else:
        return 1

def color_hex(class_num):
    return {
        4: "#1a9850",  # vert
        3: "#91cf60",  # vert clair
        2: "#fee08b",  # jaune
        1: "#d73027",  # rouge
        0: "#bdbdbd"   # gris
    }.get(class_num, "#bdbdbd")

station["SCORE_CLASSE"] = station["SCORE_FINAL"].apply(score_class)
station["SCORE_CLASS_NUM"] = station["SCORE_FINAL"].apply(score_class_num)
station["COLOR_HEX"] = station["SCORE_CLASS_NUM"].apply(color_hex)
station["ANNEE_SCORE"] = target_year

# -----------------------------
# 8) STATIONS -> GEODATAFRAME
# -----------------------------
stations_gdf = gpd.GeoDataFrame(
    station,
    geometry=gpd.points_from_xy(station["LON"], station["LAT"]),
    crs="EPSG:4326"
).to_crs("EPSG:2154")

# -----------------------------
# 9) LECTURE DE LA BASE TUP
# -----------------------------
layers = gpd.list_layers(gpkg_path)
if layers is None or len(layers) == 0:
    raise ValueError("Aucune couche trouvée dans le GPKG TUP.")

layer_name = layers.iloc[0]["name"]
tup = gpd.read_file(gpkg_path, layer=layer_name)

if tup.crs is None:
    tup = tup.set_crs("EPSG:2154")
else:
    tup = tup.to_crs("EPSG:2154")

print("Couche TUP lue :", layer_name)
print("Nombre d'unités foncières :", len(tup))

# -----------------------------
# 10) JOINTURE SPATIALE : CHAQUE UF <- STATION LA PLUS PROCHE
# -----------------------------
tup_poly = tup.copy()  # on garde les polygones d'origine
tup_cent = tup.copy()
tup_cent["geometry"] = tup_cent.geometry.centroid  # géométrie temporaire pour la proximité

join_cols = [
    "NUM_POSTE", "NOM_USUEL", "RR_ANN_MM", "ETP_ANN_MM", "ETP_MM_J",
    "TM_ANN_C", "TN_MIN_C", "TX_MAX_C",
    "S_RR", "S_TM", "S_TX", "S_TN", "S_ETP", "S_TEMP",
    "SCORE_FINAL", "SCORE_CLASSE", "SCORE_CLASS_NUM", "COLOR_HEX",
    "ETP_PART_ESTIMEE", "ANNEE_SCORE", "geometry"
]

tup_final = gpd.sjoin_nearest(
    tup_cent,
    stations_gdf[join_cols],
    how="left",
    distance_col="DIST_STATION_M"
)

# on supprime l'index de la couche des stations ajouté par sjoin_nearest
if "index_right" in tup_final.columns:
    tup_final = tup_final.drop(columns=["index_right"])

# on remet la vraie géométrie polygone à la place du centroïde
tup_final["geometry"] = tup_poly.geometry.values
tup_final = gpd.GeoDataFrame(tup_final, geometry="geometry", crs=tup_poly.crs)

tup_final["DIST_STATION_KM"] = (tup_final["DIST_STATION_M"] / 1000.0).round(2)

# -----------------------------
# 11) EXPORT UNIQUE EN GPKG POUR QGIS
# -----------------------------
out_gpkg = "/content/TUP_score_agroclimatique.gpkg"

tup_final.to_file(out_gpkg, layer="tup_score_agro", driver="GPKG")

print("\n==================== RESUME ====================")
print("Année utilisée pour le score :", target_year)
print("Nombre de stations retenues :", len(stations_gdf))
print("Nombre d'unités foncières exportées :", len(tup_final))
print("Fichier QGIS :", out_gpkg)

# téléchargement Colab
try:
    from google.colab import files
    files.download(out_gpkg)
except Exception as e:
    print("\nTéléchargement automatique non lancé.")
    print("Erreur :", e)

# -----------------------------
# 12) TELECHARGEMENT AUTOMATIQUE DANS COLAB
# -----------------------------
try:
    from google.colab import files
    files.download(out_gpkg)
    files.download(out_csv_station)
    files.download(out_csv_legend)
except Exception as e:
    print("\nTéléchargement automatique non lancé (normal hors Colab).")
    print("Erreur :", e)

import os

os.path.exists("/content/TUP_score_agroclimatique.gpkg")

!zip /content/TUP_score_agroclimatique.zip /content/TUP_score_agroclimatique.gpkg

from google.colab import files
files.download("/content/TUP_score_agroclimatique.zip")